name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: pnpm/action-setup@v4.0.0
        name: Setup pnpm
        with:
          version: latest
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: pnpm install
      - name: Unit Tests
        run: pnpm test
      - name: E2E Tests
        uses: cypress-io/github-action@v6
        with:
          start: pnpm dev
          wait-on: "http://localhost:3000"
